package util

case class pay_info(
                        id: Int,
                        version: Int,
                        order_num: String,
                        num: String,
                        batch_num: String,
                        amount: BigDecimal,
                        customer_num: String,
                        shop_num: String,
                        bank_mark: String,
                        `type `: String,
                        remark: String,
                        source_type: String,
                        status: String,
                        bank_request_num: String,
                        bank_trade_num: String,
                        auth_code: String,
                        complete_time: String,
                        can_accounted: Byte,
                        has_accounted: Byte,
                        member_num: String,
                        pay_way: String,
                        ledger_status: String,
                        ledger_rule_str: String,
                        ledger_rule_result_str: String,
                        deleted: Byte,
                        deleted_time: String,
                        gmt_create: String,
                        gmt_modify: String,
                        pay_business_one: String,
                        pay_business_two: String,
                        pay_business_three: String,
                        pay_business_four: String,
                        pay_business_five: Int,
                        prepay_id: String,
                        gmt_modify_time:String
                     )